<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Рабочий стол</title>

		<link href="<?= asset('/vendor/font-awesome/css/font-awesome.min.css') ?>" rel="stylesheet" />

		<link href="<?= asset('/assets/desktop/desktop.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/vendor/fenric-js-notify/src/notify.css') ?>" rel="stylesheet" />

		<link href="<?= asset('/vendor/jquery-ui/themes/base/jquery-ui.min.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/vendor/jquery-datetimepicker/build/jquery.datetimepicker.min.css') ?>" rel="stylesheet" />

		<link href="<?= asset('/vendor/bootstrap-3/dist/css/bootstrap.min.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/vendor/bootstrap-select/dist/css/bootstrap-select.min.css') ?>" rel="stylesheet" />

		<link href="<?= asset('/vendor/jquery-fancybox/dist/jquery.fancybox.min.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/vendor/cropper/dist/cropper.min.css') ?>" rel="stylesheet" />

		<link href="<?= asset('/vendor/codemirror/lib/codemirror.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/vendor/codemirror/theme/eclipse.css') ?>" rel="stylesheet" />
	</head>
	<body>
		<div id="desktop" class="loading"></div>
		<script src="/assets/fenric.js?<?= time() ?>"></script>

		<script src="<?= asset('/vendor/fenric-js-http-request/src/request.js') ?>"></script>
		<script src="<?= asset('/vendor/fenric-js-templating/src/bugaboo.js') ?>"></script>
		<script src="<?= asset('/vendor/fenric-js-timer/src/timer.js') ?>"></script>
		<script src="<?= asset('/vendor/fenric-js-notify/src/notify.js') ?>"></script>

		<script src="<?= asset('/assets/desktop/desktop.js') ?>"></script>
		<script src="<?= asset('/assets/desktop/desktop.init.js') ?>"></script>

		<script src="<?= asset('/vendor/jquery/dist/jquery.min.js') ?>"></script>
		<script src="<?= asset('/vendor/jquery-ui/jquery-ui.min.js') ?>"></script>
		<script src="<?= asset('/vendor/jquery-fancybox/dist/jquery.fancybox.min.js') ?>"></script>
		<script src="<?= asset('/vendor/jquery-datetimepicker/build/jquery.datetimepicker.full.min.js') ?>"></script>

		<script src="<?= asset('/vendor/bootstrap-3/dist/js/bootstrap.min.js') ?>"></script>
		<script src="<?= asset('/vendor/bootstrap-confirmation/bootstrap-confirmation.min.js') ?>"></script>
		<script src="<?= asset('/vendor/bootstrap-select/dist/js/bootstrap-select.min.js') ?>"></script>
		<script src="<?= asset('/vendor/bootstrap-select/dist/js/i18n/defaults-ru_RU.min.js') ?>"></script>

		<script src="<?= asset('/vendor/cropper/dist/cropper.min.js') ?>"></script>
		<script src="<?= asset('/vendor/chart/dist/Chart.min.js') ?>"></script>
		<script src="<?= asset('/assets/ckeditor/ckeditor.js') ?>"></script>

		<script src="<?= asset('/vendor/codemirror/lib/codemirror.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/addon/fold/xml-fold.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/addon/edit/matchbrackets.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/addon/edit/matchtags.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/addon/edit/closetag.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/addon/selection/active-line.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/mode/css/css.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/mode/javascript/javascript.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/mode/xml/xml.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/mode/htmlmixed/htmlmixed.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/mode/clike/clike.js') ?>"></script>
		<script src="<?= asset('/vendor/codemirror/mode/php/php.js') ?>"></script>

	</body>
</html>
