<?php $this->layout('layouts/main') ?>

<?php $this->start('metadata') ?>

<?php if (fenric('parameter::home.page.meta.title')) : ?>
	<title><?= e(fenric('parameter::home.page.meta.title')) ?></title>
<?php endif; ?>
<?php if (fenric('parameter::home.page.meta.author')) : ?>
	<meta name="author" content="<?= e(fenric('parameter::home.page.meta.author')) ?>" />
<?php endif; ?>
<?php if (fenric('parameter::home.page.meta.keywords')) : ?>
	<meta name="keywords" content="<?= e(fenric('parameter::home.page.meta.keywords')) ?>" />
<?php endif; ?>
<?php if (fenric('parameter::home.page.meta.description')) : ?>
	<meta name="description" content="<?= e(fenric('parameter::home.page.meta.description')) ?>" />
<?php endif; ?>
<?php if (fenric('parameter::home.page.meta.robots')) : ?>
	<meta name="robots" content="<?= e(fenric('parameter::home.page.meta.robots')) ?>" />
<?php endif; ?>
<?php if (fenric('parameter::home.page.meta.generator')) : ?>
	<meta name="generator" content="<?= e(fenric('parameter::home.page.meta.generator')) ?>" />
<?php endif; ?>

<?php $this->stop() ?>

<?php $this->start('stylesheets') ?>
<?php $this->stop() ?>

<?php $this->start('javascripts') ?>
<?php $this->stop() ?>

<div class="container">
	<h1 class="display-1 mt-3 mb-3">Home page</h1>
</div>
