<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8" />
		<?= $this->section('metadata') ?>
		<?= $this->section('stylesheets') ?>
		<link href="<?= asset('/assets/vendor/bootstrap-4.0.0/css/bootstrap.min.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/assets/vendor/fancybox-3.1.24/jquery.fancybox.min.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/assets/vendor/font-awesome-4.7.0/css/font-awesome.min.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/assets/styles.css') ?>" rel="stylesheet" />
	</head>
	<body>
		<div class="bg-faded">
			<div class="container">
				<nav class="navbar navbar-main navbar-light navbar-toggleable-md">
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main-toggle-content" aria-controls="navbar-main-toggle-content" aria-expanded="false">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="navbar-collapse collapse" id="navbar-main-toggle-content">
						<?= fenric('snippet::menu.main') ?>
					</div>
				</nav>
			</div>
		</div>
		<div class="clearfix">
			<?= $this->section('content') ?>
		</div>
		<script src="<?= asset('/assets/vendor/fenric/request/src/request.js') ?>"></script>
		<script src="<?= asset('/assets/vendor/fenric/bugaboo/src/bugaboo.js') ?>"></script>
		<script src="<?= asset('/assets/vendor/jquery-3.2.1.min.js') ?>"></script>
		<script src="<?= asset('/assets/vendor/bootstrap-4.0.0/js/bootstrap.min.js') ?>"></script>
		<script src="<?= asset('/assets/vendor/fancybox-3.1.24/jquery.fancybox.min.js') ?>"></script>
		<?= $this->section('javascripts') ?>
		<?= fenric('snippet::analytics') ?>
	</body>
</html>
