<div class="col-12 col-lg-6 mb-4 w-100">
	<div class="card h-100">

		<?php if ($publication->getPicture()) : ?>
			<a href="<?= $publication->getUri() ?>">
				<img class="card-img-top w-100" src="/upload/640x360/<?= $publication->getPicture() ?>" alt="" />
			</a>
		<?php elseif ($publication->getCover()) : ?>
			<a href="<?= $publication->getUri() ?>">
				<img class="card-img-top w-100" src="/upload/640x360/<?= $publication->getCover() ?>" alt="" />
			</a>
		<?php endif; ?>

		<div class="card-block">
			<div class="card-title">
				<div class="mb-2">
					<a class="text-reset" href="<?= $publication->getUri() ?>">
						<h4 class="mb-0"><?= $publication->getHeader() ?></h4>
					</a>
				</div>
				<div class="clearfix">
					<div class="float-left mr-3">
						<div class="small text-muted">
							<i class="fa fa-calendar-o" aria-hidden="true"></i>
							<span><?= $publication->getCreatedAt()->format('d.m.Y H:i') ?></span>
						</div>
					</div>
					<div class="float-left mr-3">
						<div class="small text-muted">
							<i class="fa fa-user-o" aria-hidden="true"></i>
							<a class="text-reset" href="<?= $publication->getUserRelatedByCreatedBy()->getUri() ?>">
								<span><?= $publication->getUserRelatedByCreatedBy()->getName() ?></span>
							</a>
						</div>
					</div>
					<div class="float-left mr-3">
						<div class="small text-muted">
							<i class="fa fa-folder-o" aria-hidden="true"></i>
							<a class="text-reset" href="<?= $publication->getSection()->getUri() ?>">
								<span><?= $publication->getSection()->getHeader() ?></span>
							</a>
						</div>
					</div>
				</div>
			</div>

			<div class="card-text">
				<div class="clearfix">
					<?= $publication->getSnippetableAnons() ?>
				</div>
			</div>

			<?php if ($publication->getPublicationTags()->count() > 0) : ?>
				<div class="mt-2 small text-muted">
					<?php foreach ($publication->getPublicationTags() as $publicationTag) : ?>
						<a class="text-reset" href="/<?= $publication->getSection()->getCode() ?>/<?= $publicationTag->getTag()->getCode() ?>/">
							<span>#<?= $publicationTag->getTag()->getHeader() ?></span>
						</a>
					<?php endforeach; ?>
				</div>
			<?php endif; ?>
		</div>

		<div class="card-footer">
			<div class="clearfix">
				<div class="float-left mr-3 small text-muted">
					<i class="fa fa-camera-retro" aria-hidden="true"></i>
					<a class="text-reset" href="<?= $publication->getUri() ?>#publication_gallery">
						<span><?= $publication->getCountPhotos() ?></span>
					</a>
				</div>
				<div class="float-left mr-3 small text-muted">
					<i class="fa fa-eye" aria-hidden="true"></i>
					<span><?= $publication->getHits() ?></span>
				</div>
			</div>
		</div>
	</div>
</div>
