<?php $this->layout('layouts/main') ?>

<?php $this->start('metadata') ?>

<?php if ($section->getMetaTitle()) : ?>
	<title><?= e($section->getMetaTitle()) ?></title>
<?php endif; ?>
<?php if ($section->getMetaAuthor()) : ?>
	<meta name="author" content="<?= e($section->getMetaAuthor()) ?>" />
<?php endif; ?>
<?php if ($section->getMetaKeywords()) : ?>
	<meta name="keywords" content="<?= e($section->getMetaKeywords()) ?>" />
<?php endif; ?>
<?php if ($section->getMetaDescription()) : ?>
	<meta name="description" content="<?= e($section->getMetaDescription()) ?>" />
<?php endif; ?>
<?php if ($section->getMetaRobots()) : ?>
	<meta name="robots" content="<?= e($section->getMetaRobots()) ?>" />
<?php endif; ?>
<?php if (fenric('parameter::home.page.meta.generator')) : ?>
	<meta name="generator" content="<?= e(fenric('parameter::home.page.meta.generator')) ?>" />
<?php endif; ?>

<?php $this->stop() ?>

<?php $this->start('stylesheets') ?>
<?php $this->stop() ?>

<?php $this->start('javascripts') ?>
<?php $this->stop() ?>

<div class="container">
	<h1 class="display-1 mt-3 mb-3"><?= $section->getHeader() ?></h1>
</div>

<?php if ($section->getContent()) : ?>
	<div class="container mt-4">
		<div class="clearfix">
			<?= $section->getSnippetableContent() ?>
		</div>
	</div>
<?php endif; ?>
