<?php $this->layout('layout') ?>

<?php $this->start('metadata') ?>
<title><?= e($section->getMetaTitle() ?: $section->getHeader()) ?></title>

<?php if ($section->getMetaAuthor()) : ?>
	<meta name="author" content="<?= e($section->getMetaAuthor()) ?>" />
<?php endif; ?>

<?php if ($section->getMetaKeywords()) : ?>
	<meta name="keywords" content="<?= e($section->getMetaKeywords()) ?>" />
<?php endif; ?>

<?php if ($section->getMetaDescription()) : ?>
	<meta name="description" content="<?= e($section->getMetaDescription()) ?>" />
<?php endif; ?>

<?php if ($section->getMetaRobots()) : ?>
	<meta name="robots" content="<?= e($section->getMetaRobots()) ?>" />
<?php endif; ?>

<?php if ($section->getMetaCanonical()) : ?>
	<link rel="canonical" href="<?= e($section->getMetaCanonical()) ?>" />
<?php endif; ?>
<?php $this->stop() ?>

<?php $this->start('stylesheets') ?>
<?php $this->stop() ?>

<?php $this->start('javascripts') ?>
<script id="dsq-count-scr" src="//fenric-cms-demo-local.disqus.com/count.js?v2" async></script>
<?php $this->stop() ?>

<div class="container mt-3">
	<nav class="breadcrumb">
		<a class="breadcrumb-item" href="/">Главная</a>
		<span class="breadcrumb-item active"><?= $section->getHeader() ?></span>
	</nav>
</div>

<div class="container mt-4">
	<h1 class="display-1"><?= $section->getHeader() ?></h1>
</div>

<?php if ($section->getPicture()) : ?>
	<div class="container mt-4">
		<img class="rounded" src="/upload/<?= $section->getPicture() ?>" />
	</div>
<?php endif; ?>

<?php if ($section->getContent()) : ?>
	<div class="container mt-4">
		<div class="clearfix">
			<?= $section->getSnippetableContent() ?>
		</div>
	</div>
<?php endif; ?>

<?php if ($publications->count() > 0) : ?>
	<div class="container mt-4">
		<div class="row">
			<?php foreach ($publications as $publication) : ?>
				<?= $this->partial('publication.card', [
					'publication' => $publication,
				]) ?>
			<?php endforeach; ?>
		</div>

		<nav>
			<?= $this->partial('publications.paginate', [
				'publications' => $publications,
			]) ?>
		</nav>
	</div>
<?php endif; ?>
