<?php $this->layout('layout') ?>

<?php $this->start('metadata') ?>
<title>Теги</title>
<?php $this->stop() ?>

<?php $this->start('stylesheets') ?>
<?php $this->stop() ?>

<?php $this->start('javascripts') ?>
<?php $this->stop() ?>

<div class="container mt-3">
	<nav class="breadcrumb">
		<a class="breadcrumb-item" href="/">Главная</a>
		<span class="breadcrumb-item active">Теги</span>
	</nav>
</div>

<div class="container mt-4">
	<h1 class="display-1">Теги</h1>
</div>

<?php if ($tags->count() > 0) : ?>
	<div class="container mt-4">
		<div class="clearfix">
			<?php foreach ($tags as $tag) : ?>
				<div class="float-left mr-3 mb-3">
					<a class="btn btn-outline-primary" href="<?= $tag->getUri() ?>"><?= $tag->getHeader() ?></a>
					<small class="text-muted"><?= $tag->getCountPublications() ?></small>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
<?php endif; ?>
