<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Рабочий стол</title>
		<link type="text/css" href="<?= asset('/assets/desktop/desktop.css') ?>" rel="stylesheet" />
		<link type="text/css" href="<?= asset('/assets/vendor/jquery-ui-1.12.1/jquery-ui.min.css') ?>" rel="stylesheet" />
		<link type="text/css" href="<?= asset('/assets/vendor/jquery-ui-1.12.1/jquery-ui.structure.min.css') ?>" rel="stylesheet" />
		<link type="text/css" href="<?= asset('/assets/vendor/jquery-datetimepicker-1.3.3/build/jquery.datetimepicker.min.css') ?>" rel="stylesheet" />
		<link type="text/css" href="<?= asset('/assets/vendor/bootstrap-3.3.7/css/bootstrap.min.css') ?>" rel="stylesheet" />
		<link type="text/css" href="<?= asset('/assets/vendor/bootstrap-select-1.12.1/css/bootstrap-select.min.css') ?>" rel="stylesheet" />
		<link type="text/css" href="<?= asset('/assets/vendor/font-awesome-4.7.0/css/font-awesome.min.css') ?>" rel="stylesheet" />
		<link type="text/css" href="<?= asset('/assets/vendor/fancybox-3.1.24/jquery.fancybox.min.css') ?>" rel="stylesheet" />
		<link type="text/css" href="<?= asset('/assets/vendor/codemirror-5.30.0/lib/codemirror.css') ?>" rel="stylesheet" />
		<link type="text/css" href="<?= asset('/assets/vendor/codemirror-5.30.0/theme/eclipse.css') ?>" rel="stylesheet" />
	</head>
	<body>
		<div id="desktop" class="loading"></div>
		<script type="text/javascript" src="<?= asset('/assets/vendor/fenric/request/src/request.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/fenric/bugaboo/src/bugaboo.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/desktop/desktop.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/desktop/desktop.init.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/jquery-3.2.1.min.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/jquery-ui-1.12.1/jquery-ui.min.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/jquery-datetimepicker-1.3.3/build/jquery.datetimepicker.full.min.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/jquery-nestedsortable-1.3.5/jquery.nestedsortable.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/bootstrap-3.3.7/js/bootstrap.min.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/bootstrap-confirmation-2.4.0/bootstrap-confirmation.min.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/bootstrap-select-1.12.1/js/bootstrap-select.min.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/bootstrap-select-1.12.1/js/i18n/defaults-ru_RU.min.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/fancybox-3.1.24/jquery.fancybox.min.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/ckeditor/ckeditor.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/lib/codemirror.js') ?>"></script>

		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/addon/fold/xml-fold.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/addon/edit/matchbrackets.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/addon/edit/matchtags.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/addon/edit/closetag.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/addon/selection/active-line.js') ?>"></script>

		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/mode/css/css.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/mode/javascript/javascript.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/mode/xml/xml.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/mode/htmlmixed/htmlmixed.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/mode/clike/clike.js') ?>"></script>
		<script type="text/javascript" src="<?= asset('/assets/vendor/codemirror-5.30.0/mode/php/php.js') ?>"></script>

		<script type="text/javascript" src="<?= asset('/assets/vendor/chart-2.7.1/chart.min.js') ?>"></script>
	</body>
</html>
