<?php

$size = function(int $size) : string
{
	$units = ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];

	for ($i = 0; $size >= 1024 && $i < 9; $i++)
	{
		$size /= 1024;
	}

	return round($size, 2) . $units[$i];
};

$sline = function(int $line, int $padding = 10) : int
{
	if (($line - $padding) <= 0)
	{
		return 1;
	}

	return $line - $padding;
};

$hline = function(int $line, int $padding = 10) : int
{
	if (($line - $padding) <= 0)
	{
		return $line;
	}

	return $padding + 1;
};

$source = function(string $file, int $line, int $padding = 10) : string
{
	$lines = file($file);

	$lines = array_map(function($value)
	{
		return e(rtrim($value));

	}, $lines);

	$lines = array_filter($lines, function($key) use($line, $padding)
	{
		return ! ($key < ($line - 1) - $padding || $key >= $line + $padding);

	}, ARRAY_FILTER_USE_KEY);

	return implode(PHP_EOL, $lines);
};

?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<link rel="stylesheet" href="<?= asset('/vendor/bootstrap-4/dist/css/bootstrap.min.css') ?>" />
		<link rel="stylesheet" href="<?= asset('/vendor/font-awesome/css/font-awesome.min.css') ?>" />
		<link rel="stylesheet" href="<?= asset('/vendor/prism/themes/prism.css') ?>" />
		<link rel="stylesheet" href="<?= asset('/vendor/prism/plugins/line-highlight/prism-line-highlight.css') ?>" />
		<link rel="stylesheet" href="<?= asset('/vendor/prism/plugins/line-numbers/prism-line-numbers.css') ?>" />
	</head>
	<body class="m-3 bg-dark">
		<div class="card mb-3">
			<div class="card-body">
				<div class="card-title">
					<h4 class="text-danger"><?= get_class($exception) ?>: <?= $exception->getMessage() ?></h4>
				</div>
				<div class="card-subtitle">
					<span class="text-muted"><?= $exception->getFile() ?> #<?= $exception->getLine() ?></span>
				</div>
				<div class="mt-3">
					<pre class="mb-0 line-numbers" data-start="<?= $sline($exception->getLine(), 8) ?>" data-line="<?= $hline($exception->getLine(), 8) ?>"><code class="language-php"><?=
						$source($exception->getFile(), $exception->getLine(), 8)
					?></code></pre>
				</div>
			</div>
		</div>

		<?php if ($tracing = $exception->getTrace()) : ?>
			<div class="card mb-3">
				<div class="card-header">
					<span>Tracing</span>
				</div>
				<div class="card-body">
					<?php foreach ($tracing as $i => $trace) : ?>
						<?php if (isset($trace['file'])) : ?>
							<?php if (isset($trace['line'])) : ?>
								<div class="mb-2">
									<div class="mb-2">
										<a href="#collapse-file-source-<?= $i ?>" data-toggle="collapse" aria-expanded="false">
											<span><?= $trace['file'] ?> #<?= $trace['line'] ?></span>
										</a>
									</div>
									<div id="collapse-file-source-<?= $i ?>" class="collapse">
										<pre class="mb-0 line-numbers" data-start="<?= $sline($trace['line'], 8) ?>" data-line="<?= $hline($trace['line'], 8) ?>"><code class="language-php"><?=
											$source($trace['file'], $trace['line'], 8)
										?></code></pre>
									</div>
								</div>
							<?php endif; ?>
						<?php endif; ?>
					<?php endforeach; ?>
				</div>
			</div>
		<?php endif; ?>

		<div class="card mb-3">
			<div class="card-header">
				<span>Debugging</span>
			</div>
			<div class="card-body">
				<table class="table">
					<tbody>
						<?php if (isset($_SERVER['SERVER_SOFTWARE'])) : ?>
							<tr>
								<td class="pl-0" width="20%">Software</td>
								<td class="pr-0"><?= $_SERVER['SERVER_SOFTWARE'] ?></td>
							</tr>
						<?php endif; ?>

						<?php if (isset($_SERVER['REQUEST_TIME_FLOAT'])) : ?>
							<tr>
								<td class="pl-0" width="20%">Speed of execution</td>
								<td class="pr-0"><?= round(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'], 3) ?>s.</td>
							</tr>
						<?php endif; ?>

						<?php if (function_exists('get_current_user')) : ?>
							<tr>
								<td class="pl-0" width="20%">Process owner</td>
								<td class="pr-0"><?= get_current_user() ?></td>
							</tr>
						<?php endif; ?>

						<?php if (function_exists('sys_getloadavg')) : ?>
							<tr>
								<td class="pl-0" width="20%">Load on system</td>
								<td class="pr-0"><?= round(sys_getloadavg()[0] * 100, 2) ?>%</td>
							</tr>
						<?php endif; ?>

						<?php if (function_exists('disk_free_space') && function_exists('disk_total_space')) : ?>
							<tr>
								<td class="pl-0" width="20%">Hard drive space</td>
								<td class="pr-0"><?= $size(disk_free_space('/')) ?> / <?= $size(disk_total_space('/')) ?></td>
							</tr>
						<?php endif; ?>
					</tbody>
				</table>
			</div>
		</div>

		<script src="<?= asset('/vendor/jquery/dist/jquery.min.js') ?>"></script>
		<script src="<?= asset('/vendor/bootstrap-4/dist/js/bootstrap.min.js') ?>"></script>
		<script src="<?= asset('/vendor/prism/prism.js') ?>"></script>
		<script src="<?= asset('/vendor/prism/components/prism-php.js') ?>"></script>
		<script src="<?= asset('/vendor/prism/plugins/line-highlight/prism-line-highlight.min.js') ?>"></script>
		<script src="<?= asset('/vendor/prism/plugins/line-numbers/prism-line-numbers.min.js') ?>"></script>
	</body>
</html>
