<?php $this->layout('layouts/main') ?>

<?php $this->start('metadata') ?>
<title><?= e($section->getMetaTitle() ?: $section->getHeader()) ?></title>

<?php if ($section->getMetaAuthor()) : ?>
	<meta name="author" content="<?= e($section->getMetaAuthor()) ?>" />
<?php endif; ?>

<?php if ($section->getMetaKeywords()) : ?>
	<meta name="keywords" content="<?= e($section->getMetaKeywords()) ?>" />
<?php endif; ?>

<?php if ($section->getMetaDescription()) : ?>
	<meta name="description" content="<?= e($section->getMetaDescription()) ?>" />
<?php endif; ?>

<?php if ($section->getMetaRobots()) : ?>
	<meta name="robots" content="<?= e($section->getMetaRobots()) ?>" />
<?php endif; ?>

<?php if ($section->getMetaCanonical()) : ?>
	<link rel="canonical" href="<?= e($section->getMetaCanonical()) ?>" />
<?php endif; ?>
<?php $this->stop() ?>

<?php $this->start('stylesheets') ?>
<?php $this->stop() ?>

<?php $this->start('javascripts') ?>
<?php $this->stop() ?>

<div class="container mt-3">
	<nav class="breadcrumb">
		<a class="breadcrumb-item" href="/">Главная</a>
		<?php if (empty($tag)) : ?>
			<span class="breadcrumb-item active"><?= $section->getHeader() ?></span>
		<?php else : ?>
			<a class="breadcrumb-item" href="<?= $section->getUri() ?>"><?= $section->getHeader() ?></a>
			<span class="breadcrumb-item active"><?= $tag->getHeader() ?></span>
		<?php endif; ?>
	</nav>
</div>

<div class="container mt-4">
	<?php if (empty($tag)) : ?>
		<h1 class="display-1"><?= $section->getHeader() ?></h1>
	<?php else : ?>
		<h1 class="display-1"><?= $tag->getHeader() ?></h1>
	<?php endif; ?>
</div>

<?php if ($section->getPicture()) : ?>
	<div class="container mt-4">
		<img class="rounded" src="/upload/<?= $section->getPicture() ?>" />
	</div>
<?php endif; ?>

<?php if ($section->getContent()) : ?>
	<div class="container mt-4">
		<div class="clearfix">
			<?= $section->getSnippetableContent() ?>
		</div>
	</div>
<?php endif; ?>

<?php if ($publications->count() > 0) : ?>
	<div class="container mt-4">
		<div class="row">
			<?php foreach ($publications as $publication) : ?>
				<?= $this->partial('publication.card', [
					'publication' => $publication,
				]) ?>
			<?php endforeach; ?>
		</div>

		<nav>
			<?= $this->partial('partials/paginate', [
				'criteria' => $publications,
			]) ?>
		</nav>
	</div>
<?php endif; ?>
