<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8" />
		<?= $this->section('metadata') ?>
		<?= $this->section('stylesheets') ?>
		<link href="<?= asset('/vendor/bootstrap-4/dist/css/bootstrap.min.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/vendor/jquery-fancybox/dist/jquery.fancybox.min.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/vendor/font-awesome/css/font-awesome.min.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/vendor/fenric-js-notify/src/notify.css') ?>" rel="stylesheet" />
		<link href="<?= asset('/assets/styles.css') ?>" rel="stylesheet" />
	</head>
	<body>
		<div class="bg-faded">
			<div class="container">
				<nav class="navbar navbar-main navbar-light navbar-toggleable-md">
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main-toggle-content" aria-controls="navbar-main-toggle-content" aria-expanded="false">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="navbar-collapse collapse" id="navbar-main-toggle-content">
						<?= fenric('snippet::menu.main') ?>
					</div>
				</nav>
			</div>
		</div>
		<div class="clearfix">
			<?= $this->section('content') ?>
		</div>
		<script src="/assets/fenric.js?<?= time() ?>"></script>

		<script src="<?= asset('/vendor/fenric-js-http-request/src/request.js') ?>"></script>
		<script src="<?= asset('/vendor/fenric-js-templating/src/bugaboo.js') ?>"></script>
		<script src="<?= asset('/vendor/fenric-js-timer/src/timer.js') ?>"></script>
		<script src="<?= asset('/vendor/fenric-js-notify/src/notify.js') ?>"></script>

		<script src="<?= asset('/vendor/jquery/dist/jquery.min.js') ?>"></script>
		<script src="<?= asset('/vendor/jquery-fancybox/dist/jquery.fancybox.min.js') ?>"></script>
		<script src="<?= asset('/vendor/bootstrap-4/dist/js/bootstrap.min.js') ?>"></script>

		<script src="<?= asset('/assets/app/components/poll/bootstrap.js') ?>"></script>
		<?= $this->section('javascripts') ?>
		<?= fenric('snippet::analytics') ?>
	</body>
</html>
